### ISSUE TITLE
QUESTION: streaming output through reqeuests 

### ISSUE THREAD

**Issue by IamWWT** [xorbitsai/inference#404]
1) i use 2 methods (codes as following) to call the xinference model service. it doesn't work for parameter "stream"=True, and has the project implemented streaming output? if true, could you provide recomended examples ?

2) when i set stream=True in the 2nd code, result is 'IteratorWrapper' not 'iterator', how can i operater  'IteratorWrapper'  to get the streaming output?

3) is there any differences of the two "model.chat" and "model.generate" in client method?

```python
    payload = {"model": model_name,
                      "messages": messages, 
                      "temperature": llm_kwargs['temperature'],  # 1.0,
                      "top_p": llm_kwargs['top_p'],  # 1.0,
                      "n": 1,
                      "stream": stream,
                      "presence_penalty": 0,
                      "frequency_penalty": 0,
                      }
        _response = requests.post(endpoint, headers=headers, json=payload, timeout=TIMEOUT_SECONDS);
        response = _response.json()['choices'][0]['message']['content']
        finish_reason = _response.json()['choices'][0]['finish_reason']
```

```shell
completion = model.chat(inputs, chat_history=payload['messages'], generate_config={"max_tokens": max_token, "stream": False})
```

**Comment by UranusSeven** [comment]
Thank you for your questions!

## 1. Example Usage:
Below is an example that demonstrates the usage of Xinference's RESTful client:

```python
client = RESTfulClient(base_url=endpoint)
model = client.get_model(model_uid=model_uid)

prompt = input("User: ")
chat_history: "List[ChatCompletionMessage]" = []
chat_history.append(ChatCompletionMessage(role="user", content=prompt))
print("Assistant: ", end="", file=sys.stdout)
response_content = ""
for chunk in model.chat(
    prompt=prompt,
    chat_history=chat_history,
    generate_config={"stream": True, "max_tokens": max_tokens},
):
    delta = chunk["choices"][0]["delta"]
    if "content" not in delta:
        continue
    else:
        response_content += delta["content"]
        print(delta["content"], end="", flush=True, file=sys.stdout)
print("\n", file=sys.stdout)
chat_history.append(
    ChatCompletionMessage(role="assistant", content=response_content)
)
```

For more details on the implementation, you can refer to the [impl](https://github.com/xorbitsai/inference/blob/8fa1630b30379385beb46010ed7ee5e5eee911f0/xinference/client.py#L332).


## 2. Usage of `IteratorWrapper`:
The `IteratorWrapper` is returned when using the Xinference's RPC client. Since `IteratorWrapper` is an asynchronous iterator, you must use `async for` instead of `for` to iterate over it.

## 3. Difference between generate and chat APIs:
The generate API is a low-level API that creates a completion for the provided prompt and parameters. On the other hand, the chat API requires an additional argument: the conversation history. This conversation history, along with the prompt, will be formatted to fit the model's input requirements (which may vary between different models) by Xinference automatically.
 
I hope this helps! If you have any more questions or need further clarification, please feel free to ask.
